services:
  grpc-client:
    depends_on:
      - grpc-server
    build: 
      context: .
      dockerfile: ./images/Containerfile.client
  grpc-server:
    build: 
      context: .
      dockerfile: ./images/Containerfile.server
