services:
  grpc-server:
    build:
      context: .
      dockerfile: ./images/Containerfile.server
    ports:
      - "8085:8085"
    restart: always
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:8085"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s
