FROM maven:3.9.9-eclipse-temurin-23 AS build


RUN apt-get update && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L -o /usr/local/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/latest/download/grpc_health_probe-linux-amd64 \
    && chmod +x /usr/local/bin/grpc_health_probe

WORKDIR /home/app/java-server-grpc

COPY apps/java-server-grpc/pom.xml /home/app/java-server-grpc
COPY apps/java-server-grpc/src /home/app/java-server-grpc/src
COPY apps/proto /home/app/proto

RUN mvn clean compile
RUN mvn clean package

FROM eclipse-temurin:23-jre
WORKDIR /usr/local/lib

COPY --from=build /home/app/java-server-grpc/target/java-server-grpc-1.0-SNAPSHOT.jar app.jar
COPY --from=build /usr/local/bin/grpc_health_probe /usr/local/bin/grpc_health_probe

EXPOSE 8085

ENTRYPOINT ["java", "-cp", "app.jar", "ai.batiinvestasi.app.App"]
CMD []