name: Deploy to Multiple EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/home/${{ secrets.SSH_USER }}/kafka/kafka-python-java-msk"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying to ${{ secrets.SSH_HOST_2 }}..."
            mkdir -p /home/${{ secrets.SSH_USER }}/kafka/kafka-python-java-msk
            cd /home/${{ secrets.SSH_USER }}/kafka/kafka-python-java-msk

            docker compose -f grpc-server-standalone-compose.yml up -d --build

            echo "Deployment completed on ${{ secrets.SSH_HOST_2 }}"
